### ISSUE TITLE
Hello world progress

### ISSUE THREAD

**Issue by paulkernfeld** [deffen3/discovery#1]
CC @mjhoy @deffen3

I got stuck for a while on "hello, world" but it was just because I wasn't running `openocd` in the same directory as `itmdump`. Then it was fine.

**Comment by deffen3** [comment]
I got tripped up for a bit because the `itmdump` cmd window wasn't updating. Might be a Windows only thing though.

**Comment by mjhoy** [comment]
just got it working.

i didn't update `cortex-m` at first so i got the familiar panic. what seemed cool is that i saw some output in the itm terminal:

```
panicked at 'called `Option::unwrap()` on a `None` value', src/06-hello-world/auxiliary/src/lib.rs:14:13
```

**Comment by mjhoy** [comment]
🤦 that was explained clearly on the next page
