### ISSUE TITLE
I went through chapter 8 already.

### ISSUE THREAD

**Issue by deffen3** [deffen3/discovery#2]
Both 6 and 7 are pretty fast as the book is just walking you through some things.

Chapter 8 is a good challenge to finish up understanding GPIO and Registers, so I'd recommend we try to get through that as well.

**Comment by paulkernfeld** [comment]
How I solved chapter 8: https://clips.twitch.tv/AgreeableEasyLarkChefFrank

**Comment by mjhoy** [comment]
hahaha that was great. nice twitch camera setup!

**Comment by deffen3** [comment]
That is a nice setup!

By the way, I think you were having an issue with RCC AHBENR selection because you were using the wrong manual.

I'm using this one: https://www.st.com/resource/en/reference_manual/dm00043574-stm32f303xb-c-d-e-stm32f303x6-8-stm32f328x8-stm32f358xc-stm32f398xe-advanced-arm-based-mcus-stmicroelectronics.pdf

**Comment by deffen3** [comment]
Oh... hah you figured it out.

**Comment by deffen3** [comment]
I love Shenzhen I/O! We can do a study group on that too.

**Comment by deffen3** [comment]
They key thing that you are missing is that moder0 does not mean moder bit 0, it means moder for PE0, or Port E Pin 0. The user guide says that the LEDs are connected to PE8 through PE15. This means you only need to moder and odr for 8 through 15.
