### ISSUE TITLE
Understanding GPIO Configuration

### ISSUE THREAD

**Issue by deffen3** [deffen3/discovery#3]
The book doesn't go into much depth on GPIO configurations. I think it deserves more attention, I have a pretty good grasp of it if you'd like to hear more when we meet. Reference Guide pg 228-244.

**Comment by mjhoy** [comment]
Something I didn't follow [here](https://rust-embedded.github.io/discovery/07-registers/rtrm.html) was:

> We are interested in the register that's at an offset of 0x18 from the base address of the GPIOE peripheral.

I was sort of with it until the `0x18`. Where does that come from?

**Comment by deffen3** [comment]
Yeah so the 0x18 is telling us what we are trying to do with the GPIOE peripheral.

For example: Page 237 11.4.1 is telling us that GPIOx_MODER can be set with an address offset of 0x00. These bits are written by software to configure the I/O mode.
00: Input mode (reset state)
01: General purpose output mode
10: Alternate function mode
11: Analog mode 

Keep scrolling down and you see that 11.4.7 GPIO port bit set/reset register (GPIOx_BSRR) (x = A..H) with Address offset: 0x18, is how we can set the actual value of the pin with Sets (set to high voltage) and Resets (reset to low voltage).

GPIO port output data register (GPIOx_ODR) (x = A..H) with Address offset: 0x14, is essentially doing the same thing as BSRR allowing you to do a Set or Reset on each pin.

**Comment by mjhoy** [comment]
gotcha. and each of the GPIO{A,B,C,D,E,F} work in the same way, and are just hooked up to different things? And where I've hooked up the SWD pin to PB3 with the female-female wire, PB3 corresponds to GPIOB pin 3?

**Comment by deffen3** [comment]
Exactly. The LEDs on our board just happen to be connected to GPIO port E.
